src/java/domain/Course.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain;

import java.util.ArrayList;
import jsfred.model.Record;
import java.util.Date;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import jsfred.constraints.Required;
import jsfred.controller.Parameters;

/**
 *
 * @author fred
 */
@Entity
@XmlRootElement
public class Course extends Record {
	@Required private String title;
	@ManyToOne private Teacher teacher;
	@ManyToMany private List<Student> students;
	@NotNull(message = "FIELD_REQUIRED") @Temporal(TemporalType.DATE) private Date startDate;
	@Min(1) private int durationDays;

	public Course() {
	}
	
	public Course(String title, Teacher teacher, Date startDate, int durationDays) {
		this.title = title;
		this.teacher = teacher;
		this.students = new ArrayList<>();
		this.startDate = startDate;
		this.durationDays = durationDays;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

//	@XmlTransient
	public List<Student> getStudents() {
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}
	
	public void addStudent(Student student) {
		students.add(student);
	}

	public void deleteStudent(Student student) {
		students.remove(student);
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public int getDurationDays() {
		return durationDays;
	}

	public void setDurationDays(int durationDays) {
		this.durationDays = durationDays;
	}

	public void setFields(Parameters parameters) {
		super.setFields(parameters);
		setTitle(parameters.getString("title"));
		setTeacher((Teacher) parameters.get("teacher"));
		setStartDate((Date) parameters.get("startDate"));
		Integer integer = (Integer) parameters.get("durationDays");
		setDurationDays(integer != null ? integer : 0);
	}

	@Override
	public String toString() {
		return String.format("%s (%s), %s", title, teacher, startDate);
	}
}

src/java/controller/CourseBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import domain.Course;
import domain.Student;
import jsfred.controller.AbstractBackingBean;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import jsfred.controller.Messages;
import static jsfred.view.ActionType.*;
import model.CourseFacade;
import model.StudentFacade;
import model.TeacherFacade;

/**
 *
 * @author fred
 */
@Named
@SessionScoped
public class CourseBean extends AbstractBackingBean<Course> {

	@EJB
	private CourseFacade courseFacade;
	@EJB
	private TeacherFacade teacherFacade;
	@EJB
	private StudentFacade studentFacade;
	
	
	public CourseBean() {
//		System.out.println("..+ CourseBean created");
	}
	
	
	@Override
	public CourseFacade getCourseFacade() {
		return courseFacade;
	}

	
	public Course newRecord() {
		return new Course();
	}

	
	@Override
	public void convert(Messages messages) throws ConversionException {
		convertToDate("startDate", messages);
		convertToRecord("teacher", teacherFacade, messages);
		convertToInteger("durationDays", messages);
		convertToLong("ref_id", messages);

		// throw exception if any conversion errors occurred
		if (messages.size() != 0) {
			throw new ConversionException(messages, getAction());
		}
	}

	
	@Override
	public void validate(Messages messages) throws ValidationException {
		// general validation (including bean validation)
		super.validate(messages);
		
		// specific validation
		// ...

		// throw exception if any validation errors occurred
		if (messages.size() != 0) {
			throw new ValidationException(messages, getAction());
		}
	}

	
	@Override
	protected String action(String action, Messages messages) {
		switch (action) {
			case "delete_student": {
				System.out.println("=== deleting student");
//				// TEST error handling
//				messages.add("delete_student", "could not delete student");
				// get student
				Long studentId = getParameters().getLong("ref_id");
				Student student = studentFacade.find(studentId);
				System.out.println("... deleting student: " + student);
				// deleting from course
				Course course = getSelectedRecord();
				course.deleteStudent(student);
				courseFacade.edit(course);
				return SHOW.pageForEntity(getEntity());
			}
			case "add_student": {
				System.out.println("=== adding student");
//				// TEST error handling
//				messages.add("add_student", "could not add student");
				// get student
				Long studentId = getParameters().getLong("ref_id");
				Student student = studentFacade.find(studentId);
				System.out.println("... adding student: " + student);
				// add to course
				Course course = getSelectedRecord();
				course.addStudent(student);
				courseFacade.edit(course);
				return SHOW.pageForEntity(getEntity());
			}
		}
		return null;
	}

	
	@Override	// until JSP recognizes the default method inherited from the BackingBean interface
	public List<Course> getRecords() {
		return super.getRecords();
	}
	
	
	public List<Student> getAvailableStudents() {
		List<Student> students = studentFacade.findAll();
		Course course = getSelectedRecord();
		students.removeIf(student -> course.getStudents().contains(student));
		return students;
	}
	
	
	public void addStudent(Student student) {
		Course course = getSelectedRecord();
		course.addStudent(student);
		courseFacade.edit(course);
	}
}

src/java/jsfred/controller/BackingBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsfred.controller;

import jsfred.model.Record;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import jsfred.model.AbstractFacade;

/**
 *
 * @author fred
 */
public interface BackingBean <T extends Record> {
	// request analysis
	public void setRequest(HttpServletRequest request);
	public Parameters getParameters();
	public Query getQuery();
	public String getEntity();
	public void setAction(String action);
	public String getAction();

	// parameter handling
	public void convert(Messages messages) throws ConversionException;
	public void validate(Messages messages) throws ValidationException;
	
	// form cancelled
	public String cancel();
	
	// action 
	public String execute(Messages messages) throws ExecutionException;
	
	public AbstractFacade<T> getCourseFacade();
	
	public T getSelectedRecord();
	
	// the bad news: default methods are not recognized by JSP...
	// so, every implementing class must override them
	public default List<T> getRecords() {
		return getCourseFacade().findAll();
	}

	public default T getRecord(long id) {
		return getCourseFacade().find(id);
	}
	
	public static class Exception extends java.lang.Exception {
		private Messages messages;
		private String page;
		
		public Exception(String message, Messages messages, String page) {
			super(message);
			this.messages = messages;
			this.page = page;
		}
		
		public Messages getMessages() {
			return messages;
		}

		public String getPage() {
			return page;
		}

		@Override
		public String toString() {
			return String.format("%s: %s", getMessage(), messages);
		}
		
		
	}
	
	public static class ConversionException extends Exception {
		public ConversionException(Messages messages, String page) {
			super("Conversion error", messages, page);
		}
	}
	
	public static class ValidationException extends Exception {
		public ValidationException(Messages messages, String page) {
			super("Validation error", messages, page);
		}
	}
	
	public static class ExecutionException extends Exception {
		public ExecutionException(Messages messages, String page) {
			super("Execution error", messages, page);
		}
	}
}

web/WEB-INF/pages/course/edit.jsp
<%-- 
    Document   : course/edit
    Created on : Nov 29, 2016, 1:30:18 PM
    Author     : fred
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="cc" tagdir="/WEB-INF/tags/cc" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<cc:mainLayout user="Fred">
    <jsp:attribute name="header">
		<h1>Course</h1>
    </jsp:attribute>

    <jsp:attribute name="footer">
		course edit
    </jsp:attribute>

    <jsp:body>
		<c:set var="course" value="${courseBean.selectedRecord}"/>
		<c:if test="${not empty course}">
			<c:set var="buttonTitle" value="Update"/>
		</c:if>
		<c:if test="${empty course}">
			<c:set var="buttonTitle" value="Add"/>
		</c:if>
		<div class="container">
			<form class="form-horizontal" method="post" action="<cc:action page="course/edit"/>">
				<input type="hidden" name=".id" value="${course.id}" />
				<input type="hidden" name=".from" value="edit" />

				<cc:input record="${course}" field="title" placeholder="Enter title">Title:</cc:input>
				<cc:select record="${course}" field="teacher" items="${teacherBean.records}">Teacher:</cc:select>
				<cc:input record="${course}" field="startDate" datePattern="dd MMM yyyy" placeholder="Enter start date">Start date:</cc:input>
				<cc:input record="${course}" field="durationDays" placeholder="Enter duration in days">Duration (days):</cc:input>

				<!--displaying the class level validation errors here-->
				<!--TODO: should be a list! (it's only one error now - the last one added to the messages wins)-->
				<div class="form-group">
					<label class="control-label col-sm-2" ></label>
					<div class="col-sm-10">
						<span class="error">${messages.get('course')}</span>
					</div>
				</div>

				<div class="form-group"> 
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-default" name="ok">${buttonTitle}</button>
						&nbsp;
						<button type="submit" class="btn btn-default" name="cancel">Cancel</button>
					</div>
				</div>
			</form>
		</div>
	</jsp:body>
</cc:mainLayout>

web/WEB-INF/pages/course/list.jsp
<%-- 
    Document   : course/list
    Created on : Nov 26, 2016, 6:06:54 PM
    Author     : fred
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="cc" tagdir="/WEB-INF/tags/cc" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<cc:mainLayout>
    <jsp:attribute name="header">
      <h1>Course</h1>
    </jsp:attribute>
	  
    <jsp:attribute name="footer">
		course list
    </jsp:attribute>
		
    <jsp:body>
		<div class="container">
			<h2>Some title concerning courses</h2>
			<p><span class="error">${messages.get("course")}</span></p>            
			<table class="table table-condensed table-striped">
				<thead>
					<tr>
						<th>title</th>
						<th>teacher</th>
						<th>students</th>
						<th>start date</th>
						<th>duration (days)</th>
					</tr>
				</thead>	
				<tbody>
					<c:if test="${empty courseBean.records}">
						<p>no courses found</p>
					</c:if>
					<c:forEach var="course" items="${courseBean.records}">
						<tr>
							<td>${course.title}</td>
							<td>${course.teacher}</td>
							<td>
								${course.students.size()}
								&nbsp;(<a href="<cc:action page="course/show?id=${course.id}"/>">edit</a>)
							</td>
							<td><fmt:formatDate value="${course.startDate}" pattern="dd MMM yyyy"/></td>
							<td>${course.durationDays}</td>
							<td><cc:edit entity="course" id="${course.id}"/></td>
							<td><cc:delete entity="course" from="list" id="${course.id}"/></td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<cc:add entity="course"/>
		</div>
    </jsp:body>
</cc:mainLayout>

web/WEB-INF/pages/course/show.jsp
<%-- 
    Document   : show
    Created on : Dec 28, 2016, 9:38:55 AM
    Author     : fred
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="cc" tagdir="/WEB-INF/tags/cc" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<cc:mainLayout user="Fred">
    <jsp:attribute name="header">
		<h1>Course</h1>
    </jsp:attribute>

    <jsp:attribute name="footer">
		course show
    </jsp:attribute>

    <jsp:body>
		<c:set var="course" value="${courseBean.selectedRecord}"/>
		<div class="container">
			<form class="form-horizontal">
				<cc:output record="${course}" field="title">Title:</cc:output>
				<cc:output record="${course}" field="teacher">Teacher:</cc:output>
				<cc:output record="${course}" field="startDate" datePattern="dd MMM yyyy">Start date:</cc:output>
				<cc:output record="${course}" field="durationDays">Duration (days):</cc:output>
				</form>

				<h3>&nbsp;</h3>
				<h3>Students in course:</h3>            
			<c:if test="${empty course.students}" var="noStudents">
				<h5>no students in course</h5>
			</c:if>
			<c:if test="${not noStudents}">
				<h4><span class="error">${messages.get("delete_student")}</span></h4>            
				<table class="table table-condensed table-striped">
					<thead>
						<tr>
							<th>first name</th>
							<th>last name</th>
							<th>address</th>
							<th>birth date</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach var="student" items="${course.students}">
							<tr>
								<td>${student.firstName}</td>
								<td>${student.lastName}</td>
								<td>${student.address}</td>
								<td><fmt:formatDate value="${student.birthDate}" pattern="dd MMM yyyy"/></td>
								<td><cc:delete entity="course" from="show" id="${course.id}" ref="student" ref_id="${student.id}"/></td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</c:if>

			<h3>&nbsp;</h3>
			<h3>Available students:</h3>            
			<div class="form-group">
				<div class="col-sm-6">
					<input class="form-control" id="search" placeholder="search" name=".search" onkeyup="doSearch();">
					<span class="error">${messages.get(field)}</span>
				</div>
			</div>
			<br/><br/>
			<h4><span class="error">${messages.get("add_student")}</span></h4>            
			<table class="table table-condensed table-striped">
				<thead>
					<tr>
						<th>first name</th>
						<th>last name</th>
						<th>address</th>
						<th>birth date</th>
					</tr>
				</thead>
				<tbody>
					<c:if test="${empty courseBean.availableStudents}">
					<p>no students available</p>
				</c:if>
				<c:forEach var="student" items="${courseBean.availableStudents}">
					<tr>
						<td>${student.firstName}</td>
						<td>${student.lastName}</td>
						<td>${student.address}</td>
						<td><fmt:formatDate value="${student.birthDate}" pattern="dd MMM yyyy"/></td>
						<td><cc:addTo entity="course" from="show" id="${course.id}" ref="student" ref_id="${student.id}"/></td>
					</tr>
				</c:forEach>
				</tbody>
			</table>
		</div>
	</jsp:body>
</cc:mainLayout>